global:
  scrape_interval: 15s
  external_labels:
    monitor: 'railway-prometheus'

scrape_configs:
  - job_name: 'local-prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otel-collector'
    scrape_interval: 5s
    static_configs:
      - targets: ['Otel-Collector:8889']

  - job_name: 'tempo'
    scrape_interval: 5s
    static_configs:
      - targets: ['Tempo:3200']

  - job_name: 'loki'
    scrape_interval: 5s
    static_configs:
      - targets: ['Loki:3100']