# Configuration file version
# See here fore more information on configuration:
# https://grafana.com/docs/grafana/latest/administration/provisioning/#example-data-source-configuration-file
apiVersion: 1

# Mark provisioned data sources for deletion if they are no longer in a provisioning file.
prune: false

# List of data sources to insert/update depending on what's available.
datasources:
  ########
  # LOKI #
  ########
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    uid: grafana_loki
    url: ${RAILWAY_LOKI_URL}
    user:
    database:
    basicAuth: false
    basicAuthUser:
    withCredentials:
    isDefault: true
    jsonData:
      derivedFields:
        - name: trace_id
          matcherRegex: 'trace_id=([0-9a-fA-F]{16,32})'
          datasourceUid: grafana_tempo
          url: '$${__value.raw}'


  ##############
  # PROMETHEUS #
  ##############
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: grafana_prometheus
    url: ${RAILWAY_PROMETHEUS_URL}
    basicAuth: false
    editable: false
    isDefault: false

  #########
  # TEMPO #
  #########
  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    uid: grafana_tempo
    url: ${RAILWAY_TEMPO_URL}
    basicAuth: false
    isDefault: false
    # https://grafana.com/docs/grafana/v11.5/datasources/tempo/configure-tempo-data-source/
    jsonData:
      tracesToLogsV2:
        datasourceUid: 'grafana_loki'
        filterByTraceID: true
        filterBySpanID: true
      tracesToMetrics:
        datasourceUid: 'grafana_prometheus'
      serviceMap:
        datasourceUid: 'grafana_prometheus'
      nodeGraph:
        enabled: true
      search:
        hide: false
      traceQuery:
        timeShiftEnabled: true
      streamingEnabled:
        search: true
